
enum class Clan (
        val clanname : String = "",
        val clanring : String = "",
        val clanskill : String = "",
        val status : Int = 0
) {
        CrabClan ("Crab","Earth", "Fitness", 30),
        CraneClan ("Crane","Air","Culture",35),
        DragonClan ("Dragon","Fire","Meditation",30),
        LionClan ("Lion","Water","Tactics",35),
        PhoenixClan ("Phoenix","Void","Theology",30),
        ScorpionClan ("Scorpion","Air","Skulduggery",35),
        UnicornClan ("Unicorn","Water","Survival",30)
}

enum class Family(
        val familyname: String = "",
        val familyrings: List<String> = listOf(""),
        val familyskills: List<String> = listOf(""),
        val glory: Int = 0,
        val wealth: Int = 0,
        val clan: String? = ""
){
        HidaFamily ("Hida", listOf("Earth","Fire"), listOf("Command", "Tactics"), 44, 4, "Crab"),
        HirumaFamily ("Hiruma", listOf("Air","Water"), listOf("Skulduggery", "Survival"), 39, 3, "Crab"),
        KaiuFamily ("Kaiu", listOf("Earth","Fire"), listOf("Smithing", "Labor"), 40, 5, "Crab"),
        KuniFamily ("Kuni", listOf("Earth","Void"), listOf("Medicine", "Theology"), 40, 4, "Crab"),
        YasukiFamily ("Yasuki", listOf("Air","Water"), listOf("Commerce", "Design"), 39, 10, "Crab"),

        AsahinaFamily ("Asahina", listOf("Water","Void"), listOf("Aesthetics", "Theology"), 40, 6, "Crane"),
        DaidojiFamily ("Daidoji", listOf("Earth","Water"), listOf("Fitness", "Tactics"), 40, 7, "Crane"),
        DojiFamily ("Doji", listOf("Air","Water"), listOf("Courtesy", "Design"), 44, 8, "Crane"),
        KakitaFamily ("Kakita", listOf("Air","Fire"), listOf("Aesthetics", "Meditation"), 44, 7, "Crane"),

        AgashaFamily ("Agasha", listOf("Fire","Void"), listOf("Medicine", "Smithing"), 40, 4, "Dragon"),
        KitsukiFamily ("Kitsuki", listOf("Air","Water"), listOf("Government", "Sentiment"), 44, 6, "Dragon"),
        MirumotoFamily ("Mirumoto", listOf("Earth","Water"), listOf("Fitness", "Tactics"), 44, 5, "Dragon"),
        TogashiFamily ("Togashi", listOf("Earth","Void"), listOf("Fitness", "Theology"), 45, 3, "Dragon"),

        AkodoFamily ("Akodo", listOf("Air","Earth"), listOf("Command", "Government"), 44, 5, "Lion"),
        IkomaFamily ("Ikoma", listOf("Air","Water"), listOf("Composition", "Performance"), 40, 5, "Lion"),
        KitsuFamily ("Kitsu", listOf("Void","Water"), listOf("Meditation", "Theology"), 40, 4, "Lion"),
        MatsuFamily ("Matsu", listOf("Earth","Fire"), listOf("Command", "Fitness"), 44, 5, "Lion"),

        AsakoFamily ("Asako", listOf("Air","Fire"), listOf("Culture", "Sentiment"), 40, 5, "Phoenix"),
        IsawaFamily ("Isawa", listOf("Fire","Void"), listOf("Meditation", "Theology"), 44, 5, "Phoenix"),
        ShibaFamily ("Shiba", listOf("Air","Void"), listOf("Fitness", "Theology"), 40, 4, "Phoenix"),
        KaitoFamily ("Kaito", listOf("Earth","Water"), listOf("Meditation", "Tactics"), 40, 5, "Phoenix"),

        BayushiFamily ("Bayushi", listOf("Air","Fire"), listOf("Courtesy", "Performance"), 40, 6, "Scorpion"),
        ShosuroFamily ("Shosuro", listOf("Air","Void"), listOf("Design", "Theology"), 40, 6, "Scorpion"),
        SoshiFamily ("Soshi", listOf("Air","Void"), listOf("Design", "Theology"), 40, 6, "Scorpion"),
        YogoFamily ("Yogo", listOf("Earth","Void"), listOf("Composition", "Theology"), 39, 4, "Scorpion"),

        IdeFamily ("Ide", listOf("Earth","Water"), listOf("Commerce", "Courtesy"), 40, 9, "Unicorn"),
        IuchiFamily ("Iuchi", listOf("Air","Void"), listOf("Meditation", "Theology"), 40, 5, "Unicorn"),
        MotoFamily ("Moto", listOf("Earth","Fire"), listOf("Command", "Survival"), 40, 6, "Unicorn"),
        ShinjoFamily ("Shinjo", listOf("Fire","Water"), listOf("Sentiment", "Survival"), 44, 8, "Unicorn"),
        UtakuFamily ("Utaku", listOf("Earth","Fire"), listOf("Survival", "Tactics"), 44, 6, "Unicorn"),

        MiyaFamily ("Miya", listOf("Air","Earth"), listOf("Courtesy", "Culture"), 44, 8, "Imperial"),
        OtomoFamily ("Otomo", listOf("Air","Water"), listOf("Culture", "Sentiment"), 43, 9, "Imperial"),
        SeppunFamily ("Seppun", listOf("Earth","Void"), listOf("Meditation", "Theology"), 45, 6, "Imperial"),

        ToritakaFamily ("Toritaka", listOf("Earth","Water"), listOf("Survival", "Meditation"), 35, 3, "Minor"),
        ShikaFamily ("Shika", listOf("Water","Fire"), listOf("Courtesy", "Culture"), 35, 5, "Minor"),
        KasugaFamily ("Kasuga", listOf("Water","Earth"), listOf("Skulduggery", "Government"), 33, 9, "Minor"),
        MantisFamily ("Mantis", listOf("Water","Fire"), listOf("Commerce", "Survival"), 36, 7, "Minor")
}

enum class School(
        val schoolname: String = "",
        val family: String = "",
        val clan: String = "",
        val schoolrings: List<String> = listOf(""),
        val skillnumber: Int = 0,
        val schoolskills: List<String> = listOf(""),
        val honor: Int = 0,
        val techniquetypes: List<String> = listOf(""),
        val roles: List<String> = listOf(""),
        val startingtechs: List<String> = listOf(""),
        val startingtechoptions: List<List<String>> = listOf(listOf("")),
        val optionchoices: List<Int> = listOf(0),
        val rank1techs: List<String> = listOf(""),
        val rank2techs: List<String> = listOf(""),
        val rank3techs: List<String> = listOf(""),
        val rank4techs: List<String> = listOf(""),
        val rank5techs: List<String> = listOf(""),
        val ability: String = ""
){
        HidaDefender ("Hida Defender", "Hida", "Crab", listOf("Earth","Water"), 5, listOf("Fitness", "Melee", "Ranged", "Unarmed", "Meditation", "Survival", "Tactics"), 40, listOf("Kata", "Rituals", "Shuji"), listOf("Bushi"), listOf("Lord Hida's Grasp (Crab)"), listOf(listOf("Striking as Earth", "Striking as Water")), listOf(1) , listOf("Rushing Avalanche Style", "Honest Assessment"), listOf("Touchstone of Courage", "Slippery Maneuvers"), listOf("Iron in the Mountains Style", "Rallying Cry"), listOf("Striking as Void", "A Samurai's Fate"), listOf("Rouse the Soul", "The Immovable Hand of Peace"), "Ignore the Cumbersome quality of armor you wear. Once per round, before making a check to resist a critical strike, you may reduce the severity of that critical strike by the physical resistance of your armor plus your school rank (to a minimum of 0)."),
        HirumaScout ("Hiruma Scout", "Hiruma", "Crab", listOf("Air","Water"), 5, listOf("Fitness", "Melee", "Ranged", "Skulduggery", "Survival", "Tactics", "Theology"), 35, listOf("Kata", "Rituals", "Shuji"), listOf("Bushi", "Shinobi"), listOf(), listOf(listOf("Pelting Hail Style", "Rushing Avalanche Style"), listOf("Striking as Air", "Striking as Water")), listOf(1, 1) , listOf("Threshold Barrier", "Slippery Maneuvers"), listOf("Skulk", "Lord Hida's Grasp (Crab)"), listOf("Deadly Sting", "Touchstone of Courage"), listOf("Noxious Cloud", "Crashing Wave Style"), listOf("Rouse the Soul", "Silencing Stroke"), "After performing an Attack action, you may change your stance. If you do, increase the TN of Attack checks by creatures of silhouette 3 or larger targeting you by your school rank until the start of your next turn."),
        KaiuEngineer ("Kaiu Engineer", "Kaiu", "Crab", listOf("Earth","Fire"), 5, listOf("Command", "Design", "Labor", "Ranged", "Medicine", "Smithing", "Theology"), 40, listOf("Kata", "Rituals", "Shuji"), listOf("Bushi", "Artisan"), listOf("Tactical Assessment", "Stirring the Embers", "Stonewall Tactics"), listOf(), listOf(0) , listOf("Pelting Hail Style", "Hawk's Precision"), listOf("Battle in the Mind", "Noxious Cloud"), listOf("Pillar of Calm", "Flowing Water Strike"), listOf("Soul Sunder", "Iron in the Mountains Style"), listOf("Sear the Wound", "Pin the Fan"), "Once per scene, when making a check to use an item you personally crafted, you may add a number of kept d set to O results equal to your school rank."),
        KuniPurifier ("Kuni Purifier", "Kuni", "Crab", listOf("Earth","Fire"), 3, listOf("Melee", "Medicine", "Sentiment", "Skulduggery", "Survival", "Theology"), 40, listOf("Invocations", "Kata", "Rituals"), listOf("Shugenja", "Bushi"), listOf("Armor of Earth", "Jade Strike", "Commune with the Spirits", "Threshold Barrier"), listOf(listOf("Striking as Earth", "Striking as Fire")), listOf(1) , listOf("Bind the Shadow", "Biting Steel"), listOf("Crimson Leaves Strike", "Symbol of Earth"), listOf("Rise Earth", "Open Hand Style"), listOf("Tomb of Jade", "Flowing Water Strike"), listOf("Earthquake", "Soul Sunder"), "Once per round, when you make a check targeting or involving a Tainted being, you may choose a number of your kept dice up to your school rank containing T symbols. Set each of these dice to a S result. You cannot use this ability if you are unsure if a being is Tainted or not."),
        YasukiMerchant ("Yasuki Merchant", "Yasuki", "Crab", listOf("Air","Earth"), 5, listOf("Commerce", "Composition", "Courtesy", "Culture", "Design", "Government", "Ranged"), 40, listOf("Kata", "Rituals", "Shuji"), listOf("Courtier"), listOf("Artisan's Appraisal"), listOf(listOf("Rustling of Leaves", "Well of Desire")), listOf(1) , listOf("Tributaries of Trade", "All in Jest"), listOf("Ebb and Flow", "Slippery Maneuvers"), listOf("Pillar of Calm", "Lord Hida's Grasp (Crab)"), listOf("Buoyant Arrival", "Bravado"), listOf("The Immovable Hand of Peace", "Lady Doji's Decree (Crane)"), "As a downtime activity, if you have access to a market, you may acquire a number of items up to your school rank of rarity 4 or lower, or a single item of up to rarity 4 plus your school rank. You do not need to make a check or expend money to acquire these items, nor do you need to forfeit or stake honor or glory for the act of acquiring them, even if they are not befitting of your station or Forbidden (though displaying them openly later is a different matter). The GM can still apply rarity adjustments as usual based on the specifics of the market available."),
        KuniWarden ("Kuni Warden", "Kuni", "Crab", listOf("Void","Fire"), 4, listOf("Command", "Melee", "Unarmed", "Meditation", "Performance", "Theology"), 34, listOf("Shuji", "Rituals", "Kiho"), listOf("Monk"), listOf("Truth Burns Through Lies"), listOf(listOf("Cleansing Spirit", "Flame Fist"), listOf("Cleansing Rite", "Threshold Barrier")), listOf(1, 1) , listOf("Courtier's Resolve", "The Body is an Anvil"), listOf("Crimson Leaves Strike", "Coiling Serpent Style"), listOf("Thunderclap Strike", "Rallying Cry"), listOf("Bravado", "Death Touch"), listOf("Striking as Void", "Sear the Wound"), "Suppressing Blows: When you perform an Attack action check using Martial Arts (Melee) or Martial Arts (Unarmed), you may spend O as follows: O+: One character per O spent this way who is in range of the weapon you used suffers the Silenced condition. You can spend a maximum number of O this way up to your school rank."),
        YasukiYojimbo ("Yasuki Yojimbo", "Yasuki", "Crab", listOf("Earth","Water"), 5, listOf("Melee", "Ranged", "Tactics", "Commerce", "Courtesy", "Seafaring", "Survival"), 50, listOf("Shuji", "Rituals", "Kata"), listOf("Bushi"), listOf("Crescent Moon Style"), listOf(listOf("Honest Assessment", "Well of Desire")), listOf(1) , listOf("Iron Forest Style", "Trip the Leg"), listOf("Touchstone of Courage", "Unyielding Terms"), listOf("All Shall Fear Me", "Pillar of Calm"), listOf("Soul Sunder", "A Samurai's Fate"), listOf("Rouse the Soul", "Striking as Void"), "Claws of the Crab: When you successfully perform the Guard action (Core p264) you may spend O as follows: O+: If you succeed, you may guard one additional character in range per O spent this way. You can spend a maximum number of O this way up to your school rank."),

        AsahinaArtificer ("Asahina Artificer", "Asahina", "Crane", listOf("Air","Fire"), 3, listOf("Aesthetics", "Courtesy", "Culture", "Design", "Games", "Theology"), 50, listOf("Invocations", "Rituals", "Shuji"), listOf("Shugenja", "Artisan"), listOf("Commune with the Spirits", "Cleansing Rite"), listOf(listOf("Blessed Wind", "Armor of Radience", "Inari's Blessing", "Reflections of P'an Ku", "Token of Memory")), listOf(3) , listOf("Path to Inner Peace", "Artisan's Appraisal"), listOf("Grasp of the Air Dragon", "Tea Ceremony"), listOf("Wings of the Phoenix", "Vapor of Nightmares"), listOf("Rise, Air", "Bend with the Storm"), listOf("Ever Changing Waves", "Buoyant Arrival"), "When making a check to mystically summon an illusion or to summon, augment, or awaken an object, you may add a number of kept d set to O results equal to your school rank."),
        DaidojiIronWarrior ("Daidoji Iron Warrior", "Daidoji", "Crane", listOf("Earth","Water"), 5, listOf("Command", "Courtesy", "Culture", "Fitness", "Government", "Melee", "Tactics"), 55, listOf("Kata", "Rituals", "Shuji"), listOf("Bushi"), listOf("Iron Forest Style"), listOf(listOf("Striking as Earth", "Striking as Water")), listOf(1) , listOf("Crescent Moon Style", "Stonewall Tactics"), listOf("Flowing Water Strike", "Lady Doji's Decree (Crane)"), listOf("Crashing Wave Style", "Ebb and Flow"), listOf("Striking as Void", "A Samurai's Fate"), listOf("Rouse the Soul", "The Immovable Hand of Peace"), "Once per round, when another character within range of one of your readied melee weapons would suffer physical damage, you may intercept. If you do, you may suffer fatigue up to your school rank to reduce the damage the target suffers by twice that amount."),
        DojiDiplomat ("Doji Diplomat", "Doji", "Crane", listOf("Air","Water"), 5, listOf("Aesthetics", "Composition", "Courtesy", "Culture", "Design", "Government", "Ranged"), 50, listOf("Kata", "Rituals", "Shuji"), listOf("Courtier"), listOf("Lady Doji's Decree (Crane)"), listOf(listOf("Cadence", "Shallow Waters", "Whispers of Court")), listOf(1) , listOf("Civility Foremost", "Tea Ceremony"), listOf("The Wind Blows Both Ways", "Artisan's Appraisal"), listOf("Regal Bearing", "Ebb and Flow"), listOf("Bend with the Storm", "Pillar of Calm"), listOf("Buoyant Arrival", "The Immovable Hand of Peace"), "Once per scene when making a check to persuade or influence someone, you may add a number of kept d set to O results equal to your school rank."),
        KakitaDuelist ("Kakita Duelist", "Kakita", "Crane", listOf("Air","Earth"), 5, listOf("Courtesy", "Design", "Fitness", "Melee", "Meditation", "Sentiment", "Smithing"), 50, listOf("Kata", "Rituals", "Shuji"), listOf("Bushi", "Artisan"), listOf("Iaijutsu Cut: Rising Blade"), listOf(listOf("Shallow Waters", "Weight of Duty")), listOf(1) , listOf("Iaijutsu Cut: Crossing Blade", "Cadence"), listOf("All Arts Are One", "Thunderclap Strike"), listOf("A Samurai's Fate", "Heartpiercing Strike"), listOf("Striking as Void", "Pillar of Calm"), listOf("Rouse the Soul", "Soul Sunder"), "Once per round, you may increase or decrease the severity of a critical strike you inflict by an amount up to your school rank."),
        KakitaSwordsmith ("Kakita Swordsmith", "Kakita", "Crane", listOf("Air","Fire"), 5, listOf("Aesthetics", "Melee", "Courtesy", "Culture", "Sentiment", "Smithing", "Theology"), 55, listOf("Kata", "Rituals", "Shuji"), listOf("Artisan", "Courtier"), listOf("Artisan's Appraisal"), listOf(listOf("Soaring Slice", "Striking as Air", "Striking as Fire")), listOf(1) , listOf("Blessing of Steel", "Well of Desire"), listOf("Ebb and Flow", "Tributaries of Trade"), listOf("All Arts Are One", "Dazzling Performance"), listOf("Soul Sunder", "Bravado"), listOf("Buoyant Arrival", "Striking as Void"), "Kakita Pattern: You can apply this item pattern (Shadowlands p109) to any bladed weapon you craft. Sacred Art of Steel: Once per game session when you make a check to craft, improve or maintain a weapon, you may add a number of kept d set to O results equal to your school rank."),
        DaidojiSpymaster ("Daidoji Spymaster", "Daidoji", "Crane", listOf("Air","Earth"), 5, listOf("Command", "Courtesy", "Culture", "Government", "Performance", "Sentiment", "Skulduggery"), 35, listOf("Kata", "Rituals", "Shuji"), listOf("Courtier", "Shinobi"), listOf("Ancestry Unearthed"), listOf(listOf("Like a Ghost", "Skulk"), listOf("Striking as Air", "Striking as Earth")), listOf(1, 1) , listOf("Lady Doji's Decree (Crane)", "Weight of Duty"), listOf("What's Yours is Mine", "Treaty Signing"), listOf("Hidden in Smoke", "Open Hand Style"), listOf("Cunning Distraction", "Wolf's Proposal"), listOf("Noxious Cloud", "Bend with the Storm"), "Incisive Insight: Once per scene, when making a check for a Scheme action targeting another character, you may receive a number of strife up to your school rank to reduce the TN by that amount (to a minimum of 1)."),
        DojiBureaucrat ("Doji Bureaucrat", "Doji", "Crane", listOf("Earth","Water"), 5, listOf("Command", "Composition", "Courtesy", "Culture", "Games", "Government", "Meditation"), 55, listOf("Rituals", "Shuji"), listOf("Courtier"), listOf("Courtier's Resolve", "Stonewall Tactics"), listOf(), listOf(0) , listOf("Treaty Signing", "Beware the Smallest Mouse"), listOf("The Wind Blows Both Ways", "Unyielding Terms"), listOf("Hidden in Smoke", "All Shall Fear Me"), listOf("The Immovable Hand of Peace", "Rallying Cry"), listOf("Bend with the Storm", "Formal Tea Ceremony"), "Procedure and Protocol: When you cause a character to receive strife as a result of a check using a social approach, that character suffers additional strife equal to your school rank."),

        AgashaMystic ("Agasha Mystic", "Agasha", "Dragon", listOf("Earth","Water"), 3, listOf("Fitness", "Unarmed", "Medicine", "Meditation", "Smithing", "Theology"), 40, listOf("Invocations", "Rituals", "Shuji"), listOf("Shugenja"), listOf("Path to Inner Peace", "Jurojin's Balm", "Cleansing Rite", "Commune with the Spirits"), listOf(listOf("Fires from Within", "Tetsubo of Earth")), listOf(1) , listOf("Heart of the Water Dragon", "Divination"), listOf("Power of the Earth Dragon", "Touchstone of Courage"), listOf("Rise, Earth", "Earth Becomes Sky"), listOf("Ever Changing Waves", "Rise, Water"), listOf("Sear the Wound", "Earthquake"), "When performing an invocation, you may choose a different ring with which to make the check. While using this school ability, you cannot activate O of the original Element of the invocation, but you can activate O for the new Element. You can use this school ability a number of times per game session up to your school rank."),
        KitsukiInvestigator ("Kitsuki Investigator", "Kitsuki", "Dragon", listOf("Air","Earth"), 5, listOf("Culture", "Government", "Melee", "Medicine", "Sentiment", "Skulduggery", "Survival"), 45, listOf("Kata", "Rituals", "Shuji"), listOf("Courtier", "Bushi"), listOf("Shallow Waters"), listOf(listOf("Striking as Air", "Tactical Assessment")), listOf(1) , listOf("Slippery Maneuvers", "Honest Assessment"), listOf("All Arts Are One", "Feigned Opening"), listOf("Regal Bearing", "Battle in the Mind"), listOf("Sear the Wound", "Bravado"), listOf("Wolf's Proposal", "Crashing Wave Style"), "When performing a check to investigate with any skill (see The Art of Investigation, on page 170), you may treat your ranks in the skill you are using as being equal to your school rank. If your ranks in the skill are equal to or higher than your school rank, or if you have 5 ranks in the skill, you may add a kept d set to an O result instead."),
        MirumotoNitenAdept ("Mirumoto Niten Adept", "Mirumoto", "Dragon", listOf("Earth","Fire"), 5, listOf("Command", "Composition", "Fitness", "Melee", "Meditation", "Tactics", "Theology"), 50, listOf("Kata", "Rituals", "Shuji"), listOf("Bushi"), listOf("Dazzling Performance"), listOf(listOf("Striking as Fire", "Striking as Water", "Striking as Earth")), listOf(1) , listOf("Iaijutsu Cut: Rising Blade", "Stirring the Embers"), listOf("Heartpiercing Strike", "Slippery Maneuvers"), listOf("Pillar of Calm", "Commune with the Spirits"), listOf("Striking as Void", "Crashing Wave Style"), listOf("Sear the Wound", "Rouse the Soul"), "Once per round during a duel or skirmish when you are targeted by an Attack check with a melee weapon, you may use one of your weapons readied in a one-handed grip (or one of your hands, if it is empty) to ward or trap. If you ward, the attacker must reroll dice containing S or E up to your school rank. If you trap, reduce the TN of your next Attack check against the attacker this scene by your school rank (to a minimum of 1). You cannot choose this weapon for Attack actions until the end of your next turn."),
        TogashiTattooedOrder ("Togashi Tattooed Order", "Togashi", "Dragon", listOf("Earth","Void"), 4, listOf("Fitness", "Melee", "Unarmed", "Meditation", "Survival", "Theology"), 40, listOf("Kiho", "Shuji", "Rituals"), listOf("Monk"), listOf("Lord Togashi's Insight (Dragon)"), listOf(listOf("Earthen Fist", "Earth Needs No Eyes", "Flame Fist", "Ki Protection", "Water Fist")), listOf(1) , listOf("Way of the Earthquake", "Honest Assessment"), listOf("Open-Hand Style", "Stirring the Embers"), listOf("Death Touch", "All Arts Are One"), listOf("Touch the Void Dragon", "Pillar of Calm"), listOf("Rouse the Soul"), "You have one mystical tattoo that empowers your kiho, and gain more as your school rank increases. When you make a check to activate a kiho linked to one of your mystical tattoos, if you succeed, add additional bonus successes equal to your school rank. Select a natural motif for your first tattoo and choose one kiho for which you meet the prerequisites that are linked to the tattoo. If you have not learned it, you learn that kiho (without paying its XP cost). You cannot choose the same kiho multiple times this way. Each time your school rank increases, you gain one additional tattoo this way."),
        MirumotoTaoistBlade ("Mirumoto Taoist Blade", "Mirumoto", "Dragon", listOf("Void","Water"), 4, listOf("Labor", "Melee", "Unarmed", "Meditation", "Survival", "Theology"), 48, listOf("Kata", "Rituals", "Kiho"), listOf("Bushi", "Monk"), listOf("Water Fist"), listOf(listOf("Iaijutsu Cut: Rising Blade", "Soaring Slice", "Striking as Water")), listOf(2) , listOf("Crescent Moon Style", "Ki Protection"), listOf("Flowing Water Strike", "Iaijutsu Cut: Crossing Blade"), listOf("Crimson Leaves Strike", "Still the Elements"), listOf("Striking as Void", "Crashing Wave Style"), listOf("Touch the Void Dragon", "Way of the Edgeless Sword"), "Sharpened Ki: Your kiho that affect your unarmed attack profiles also apply to weapons you wield in a one-handed grip. When you succeed on a check to activate a kiho that affects your unarmed attack profiles or a weapon you wield in a one handed grip, add bonus successes equal to your school rank."),
        TogashiChronicler ("Togashi Chronicler", "Togashi", "Dragon", listOf("Earth","Water"), 4, listOf("Culture", "Fitness", "Labor", "Unarmed", "Meditation", "Performance"), 40, listOf("Shuji", "Rituals", "Kata"), listOf("Courtier", "Monk"), listOf("Divination"), listOf(listOf("Cleansing Spirit", "Ki Protection"), listOf("Honest Assessment", "Truth Burns Through Lies")), listOf(1, 1) , listOf("Lord Togashi's Insight (Dragon)", "Beware the Smallest Mouse"), listOf("All Arts Are One", "Open Hand Style"), listOf("The Great Silence", "The Ties that Bind"), listOf("Breaking Blow", "Foreseen Need"), listOf("Death Touch", "The Immovable Hand of Peace"), "A Grain of Truth: Once per scene after you succeed on a Social skill check, you may choose a kiho with a prerequisite up to your school rank (whether you know it or not). You gain the benefits of its Enhancement Effect (see Core p183) as if you had successfully activated it. This effect persists until the end of the scene."),

        AkodoCommander ("Akodo Commander", "Akodo", "Lion", listOf("Earth","Water"), 5, listOf("Command", "Fitness", "Government", "Melee", "Ranged", "Meditation", "Tactics"), 50, listOf("Kata", "Rituals", "Shuji"), listOf("Bushi"), listOf("Lord Akodo's Roar (Lion)"), listOf(listOf("Striking as Earth", "Striking as Water")), listOf(1) , listOf("Iron Forest Style", "Honest Assessment"), listOf("Rallying Cry", "Lightning Raid"), listOf("A Samurai's Fate", "Touchstone of Courage"), listOf("Rouse the Soul", "Disappearing World Style"), listOf("Bend with the Storm", "Striking as Void"), "When you succeed at an Attack or Support action check, you may remove an amount of strife from yourself up to your school rank. For each strife you remove this way, add that one bonus success to the check and receive 1 fatigue."),
        IkomaBard ("Ikoma Bard", "Ikoma", "Lion", listOf("Fire","Water"), 5, listOf("Composition", "Courtesy", "Culture", "Ranged", "Performance", "Sentiment", "Tactics"), 45, listOf("Kata", "Rituals", "Shuji"), listOf("Courtier"), listOf("Warrior's Resolve", "Fanning the Flames", "Tributaries of Trade"), listOf(), listOf(0) , listOf("Slippery Maneuvers", "Soaring Slice"), listOf("Dazzling Performance", "Spinning Blades Style"), listOf("Rallying Cry", "Regal Bearing"), listOf("Sear the Wound", "Pillar of Calm"), listOf("Bend with the Storm", "Buoyant Arrival"), "Once per scene, after you perform a check using a Social skill that targets one or more characters, you may agitate or console: If you agitate, transfer strife up to twice your school rank from yourself to your targets (divided among them as you choose). If you console, transfer strife up to twice your school rank from your targets (divided among them as you choose) to yourself."),
        KitsuMedium ("Kitsu Medium", "Kitsu", "Lion", listOf("Void","Water"), 3, listOf("Courtesy", "Government", "Meditation", "Performance", "Survival", "Theology"), 50, listOf("Invocations", "Rituals", "Shuji"), listOf("Shugenja"), listOf("Commune with the Spirits", "Cleansing Rite", "Ancestry Unearthed"), listOf(listOf("The Rushing Wave", "Path to Inner Peace", "Biting Steel")), listOf(2) , listOf("Courage of Seven Thunders", "Heart of the Water Dragon"), listOf("Hands of the Tides", "Fanning the Flames"), listOf("Rise, Earth", "Ebb and Flow"), listOf("Wrath of Kaze-no-Kami", "Bravado"), listOf("Sear the Wound", "Buoyant Arrival"), "Once per scene, you may importune one invocation (see Importune Invocations, on page 189) with a school rank prerequisite up to your school rank without making the sacrifices usually required and without the usual TN increase."),
        MatsuBerserker ("Matsu Berserker", "Matsu", "Lion", listOf("Earth","Fire"), 5, listOf("Command", "Fitness", "Labor", "Melee", "Ranged", "Unarmed", "Survival"), 55, listOf("Kata", "Rituals", "Shuji"), listOf("Bushi"), listOf("Stirring the Embers"), listOf(listOf("Rushing Avalanche Style", "Spinning Blades Style")), listOf(1) , listOf("Lord Akodo's Roar (Lion)", "Stonewall Tactics"), listOf("Heartpiercing Strike", "Fanning the Flames"), listOf("Disappearing World Style", "Rallying Cry"), listOf("Striking as Void", "Bravado"), listOf("Sear the Wound", "Rouse the Soul"), "After you suffer a critical strike or unmask, you may suffer the Enraged condition to remove an amount of fatigue from yourself equal to your school rank."),
        KitsuMedic ("Kitsu Medic", "Kitsu", "Lion", listOf("Earth","Water"), 5, listOf("Command", "Fitness", "Melee", "Unarmed", "Medicine", "Sentiment", "Survival"), 44, listOf("Shuji", "Rituals", "Kata"), listOf("Artisan", "Bushi"), listOf("Stonewall Tactics"), listOf(listOf("Crescent Moon Style", "Striking as Earth", "Striking as Water"), listOf("Cleansing Rite", "Threshold Barrier")), listOf(1, 1) , listOf("Commune with the Spirits", "Honest Assessment"), listOf("Flowing Water Strike", "Rushing Avalanche Style"), listOf("Iron in the Mountains Style", "Touchstone of Courage"), listOf("Crashing Wave Style", "A Samurai's Fate"), listOf("Rouse the Soul", "Sear the Wound"), "Field Medicine: When you perform a Medicine check to remove fatigue or a condition from a friendly character, that character removes additional fatigue up to your school rank"),
        IkomaShadow ("Ikoma Shadow", "Ikoma", "Lion", listOf("Air","Fire"), 5, listOf("Courtesy", "Culture", "Government", "Melee", "Ranged", "Skulduggery", "Survival"), 40, listOf("Shuji", "Rituals", "Kata"), listOf("Courtier", "Shinobi"), listOf("Whispers of Court", "Skulk"), listOf(listOf("Hawk's Precision", "Warrior's Resolve")), listOf(1) , listOf("What's Yours is Mine", "Rustling of Leaves"), listOf("Crackling Laughter", "The Wind Blows Both Ways"), listOf("Artful Alibi", "All Arts Are One"), listOf("Deceitful Strike", "Bravado"), listOf("Silent Elimination", "Pin the Fan"), "Victory Before Honor: Once per scene when performing a check, you may stake an amount of honor no greater than your school rank to reroll a number of dice equal to twice the amount of honor staked. For each rerolled die result that does not contain a S or E, you forfeit one staked honor"),

        AsakoLoremaster ("Asako Loremaster", "Asako", "Phoenix", listOf("Air","Earth"), 5, listOf("Culture", "Government", "Unarmed", "Medicine", "Performance", "Sentiment", "Theology"), 45, listOf("Kata", "Rituals", "Shuji"), listOf("Courtier"), listOf("Civility Foremost"), listOf(listOf("Ancestry Unearthed", "Cadence")), listOf(1) , listOf("Open Hand Style", "Divination"), listOf("All Arts Are One", "Tea Ceremony"), listOf("Pillar of Calm", "Ebb and Flow"), listOf("Cleansing Spirit", "Wolf's Proposal"), listOf("Still the Elements", "Bend With The Storm"), "When performing a Scholar skill check, you may treat your ranks in the skill as being equal to your school rank. If your ranks in that Scholar skill are equal to or higher than your school rank, or if you have 5 ranks in the skill, you may add one kept d set to an O result instead."),
        IsawaElementalist ("Isawa Elementalist", "Isawa", "Phoenix", listOf("Any","Any"), 3, listOf("Composition", "Courtesy", "Medicine", "Meditation", "Performance", "Theology"), 40, listOf("Invocations", "Rituals", "Shuji"), listOf("Shugenja"), listOf("Commune with the Spirits", "Divination"), listOf(listOf("Extinguish", "Grasp of Earth", "Path to Inner Peace", "Tempest of Air")), listOf(3) , listOf("Dance of Seasons", "Cleansing Rite"), listOf("Fanning the Flames", "Fury of Osano-Wo"), listOf("Wings of the Phoenix", "Strike the Tsunami"), listOf("Wrath of Kaze-no-Kami", "Rise, Flame"), listOf("Earthquake", "Rouse the Soul"), "Once per scene when making the check to activate an invocation technique, before rolling dice, you may reduce the TN of the check by your school rank."),
        ShibaGuardian ("Shiba Guardian", "Shiba", "Phoenix", listOf("Earth","Water"), 5, listOf("Courtesy", "Fitness", "Melee", "Meditation", "Survival", "Tactics", "Theology"), 45, listOf("Kata", "Rituals", "Shuji"), listOf("Bushi", "Courtier"), listOf("Lord Shiba's Valor (Phoenix)"), listOf(listOf("Striking as Earth", "Striking as Water")), listOf(1) , listOf("Civility Foremost", "Stirring the Embers"), listOf("Rallying Cry", "Slippery Maneuvers"), listOf("A Samurai's Fate", "Touchstone of Courage"), listOf("The Immovable Hand of Peace", "Touch the Void Dragon"), listOf("Way of the Edgeless Sword", "Rouse the Soul"), "Once per scene, when a character at range 0-3 makes a check that contains 1 or more Strife symbols, you may negate all of those Strife symbols. Then, that character removes strife and fatigue equal to your school rank."),
        KaitoShrineKeeper ("Kaito Shrine Keeper", "Kaito", "Phoenix", listOf("Air","Water"), 4, listOf("Fitness", "Ranged", "Meditation", "Performance", "Smithing", "Theology"), 45, listOf("Kata", "Rituals", "Shuji"), listOf("Monk"), listOf("Hawk's Precision", "Tempest of Air"), listOf(listOf("Cleansing Rite", "Commune with the Spirits", "Threshold Barrier")), listOf(2) , listOf("Bind the Shadow", "Striking as Air"), listOf("Grasp of the Air Dragon", "Divination"), listOf("Breath of Wind Style", "Flowing Water Strike"), listOf("Rise, Air", "Soul Sunder"), listOf("Tomb of Jade", "Pin the Fan"), "As an action, you may augment one of your arrows with a prayer to the kami. Make the check to perform one invocation you know, reducing the TN by your school rank, and record the result. The arrow gains the Sacred quality, and remains infused with the invocation until the end of the scene. After you perform an Attack action using the arrow (or fire it at a location, at the GM's discretion), you may resolve the effects of the invocation from the place the arrow landed. You may spend O+ to delay resolving the effects of the invocation for 1 round per O spent this way, and may spend O O from a failed check to affect one target of the attack that you missed."),
        AsakoInquisitor ("Asako Inquisitor", "Asako", "Phoenix", listOf("Fire","Void"), 3, listOf("Courtesy", "Meditation", "Melee", "Unarmed", "Performance", "Theology"), 35, listOf("Invocations", "Shuji", "Rituals"), listOf("Courtier", "Shugenja"), listOf("Cleansing Rite", "Commune with the Spirits", "Divination", "Cadence", "Truth Burns Through Lies"), listOf(), listOf(0) , listOf("Threshold Barrier", "Weight of Duty"), listOf("Essence of Jade", "Open Hand Style"), listOf("Regal Bearing", "Touchstone of Courage"), listOf("The Soul's Blade", "Bravado"), listOf("Striking as Void", "Rouse the Soul"), "Traces of Passage: Once per scene as a Support action, you may scry to detect any supernatural abilities used at range 0-3 in the last day (such as invocations, maho and kiho). Reduce the TN of your checks to investigate this phenomenon by your school rank."),
        ShibaArtist ("Shiba Artist", "Shiba", "Phoenix", listOf("Fire","Void"), 5, listOf("Aesthetics", "Composition", "Courtesy", "Culture", "Design", "Performance", "Smithing"), 50, listOf("Shuji", "Rituals", "Kata"), listOf("Artisan"), listOf("Tea Ceremony"), listOf(listOf("Assess Strengths", "Courtier's Resolve", "Fun and Games")), listOf(2) , listOf("Offend the Sensibilities", "Fun and Games"), listOf("The Wind Blows Both Ways", "Civility Foremost"), listOf("Formal Tea Ceremony", "All Arts Are One"), listOf("Rouse the Soul", "Hidden in Smoke"), listOf("Bend with the Storm", "Buoyant Arrival"), "Architect of Tranquility: Once per scene after you succeed at an Artisan skill check, you may choose a number of characters in the scene equal to your school rank. Each chosen character removes 3 strife."),

        BayushiManipulator ("Bayushi Manipulator", "Bayushi", "Scorpion", listOf("Air","Fire"), 5, listOf("Command", "Courtesy", "Design", "Unarmed", "Performance", "Sentiment", "Skulduggery"), 35, listOf("Kata", "Rituals", "Shuji"), listOf("Courtier"), listOf("Lord Bayushi's Whispers (Scorpion)"), listOf(listOf("Cadence", "Rustling of Leaves")), listOf(1) , listOf("Fanning the Flames", "Weight of Duty"), listOf("Dazzling Performance", "Veiled Menace Style"), listOf("Wolf's Proposal", "Skulk"), listOf("Buoyant Arrival", "Deadly Sting"), listOf("Bend with the Storm", "Sear the Wound"), "When you exploit a target's disadvantage (see Turning Advantages and Disadvantages, page 100) as part of a Scheme action, you do not need to spend a Void point, and you may reroll additional dice up to your school rank."),
        ShosuroInfiltrator ("Shosuro Infiltrator", "Shosuro", "Scorpion", listOf("Air","Earth"), 5, listOf("Courtesy", "Fitness", "Games", "Melee", "Unarmed", "Performance", "Skulduggery"), 30, listOf("Kata", "Rituals", "Shuji"), listOf("Shinobi", "Courtier"), listOf("Deadly Sting"), listOf(listOf("Whispers of Court", "Sensational Distraction")), listOf(1) , listOf("Veiled Menace Style", "Skulk"), listOf("Lord Bayushi's Whispers (Scorpion)", "Noxious Cloud"), listOf("Bravado", "Dazzling Performance"), listOf("Silencing Stroke", "A Samurai's Fate"), listOf("Buoyant Arrival", "Sear the Wound"), "While performing an Attack action against a target who is Compromised, Incapacitated, Unconscious, or unaware of your presence, treat the damage and deadliness of your weapon as being increased by your school rank."),
        SoshiIllusionist ("Soshi Illusionist", "Soshi", "Scorpion", listOf("Air","Water"), 3, listOf("Courtesy", "Fitness", "Games", "Performance", "Skulduggery", "Theology"), 30, listOf("Invocations", "Rituals", "Shuji"), listOf("Shugenja", "Courtier", "Shinobi"), listOf("Commune with the Spirits", "All in Jest"), listOf(listOf("Bo of Water", "Cloak of Night", "Nature's Touch", "Token of Memory")), listOf(3) , listOf("Mask of Wind", "Skulk"), listOf("Vapor of Nightmares", "Lord Bayushi's Whispers (Scorpion)"), listOf("False Realm of the Fox Spirits", "Noxious Cloud"), listOf("Deadly Sting ", "Rise, Air"), listOf("Buoyant Arrival", "Silencing Stroke"), "While you are performing an invocation technique or channeling, characters with a vigilance lower than or equal to your school rank plus one cannot detect any physical sign that you are in the act of invoking the spirits. They can still observe effects of the invocation, however. Increase the TN of Theology checks to detect or study your supernatural activities by your school rank."),
        YogoWardmaster ("Yogo Wardmaster", "Yogo", "Scorpion", listOf("Earth","Water"), 3, listOf("Composition", "Fitness", "Melee", "Unarmed", "Meditation", "Theology"), 40, listOf("Invocations", "Rituals", "Shuji"), listOf("Shugenja"), listOf("Shallow Waters", "Commune with the Spirits", "Threshold Barrier"), listOf(listOf("Jade Strike", "Grasp of Earth", "The Rushing Wave")), listOf(2) , listOf("Civility Foremost", "Path to Inner Peace"), listOf("Ebb and Flow", "Embrace of Kenro-ji-Jin"), listOf("Open Hand Style", "Earth Becomes Sky"), listOf("Skulk", "Rise, Water"), listOf("Deadly Sting", "Tomb of Jade"), "You can have a number of additional wards with prepared invocations (Core p190) up to your school rank. Decoding or using one of your wards requires any other character to make a Theology (Void) check with TN equal to your school rank."),
        YogoPreserver ("Yogo Preserver", "Yogo", "Scorpion", listOf("Fire","Void"), 3, listOf("Aesthetics", "Courtesy", "Melee", "Sentiment", "Skulduggery", "Theology"), 38, listOf("Invocations", "Shuji", "Rituals"), listOf("Shugenja"), listOf("By the Light of the Lord Moon", "Embrace of Kenro-Ji-Jin", "Yari of Air", "Craft Shikigami", "Threshold Barrier"), listOf(), listOf(0) , listOf("Cloak of Night", "Reflections of P'an Ku"), listOf("Hands of the Tides", "Skulk"), listOf("Vapor of Nightmares", "Wings of the Phoenix"), listOf("Silencing Stroke", "Suijin's Embrace"), listOf("Ever Changing Waves", "Tomb of Jade"), "Warded Shikigami: You can hyave a number of additional shikigami (Shadowlands p115) up to your school rank. Once per scene, after you perform an action, you may instruct one of your shikigami to perform an action, for which it benefits from your assistance."),
        BayushiDeathdealer ("Bayushi Deathdealer", "Bayushi", "Scorpion", listOf("Air","Fire"), 5, listOf("Command", "Courtesy", "Fitness", "Melee", "Ranged", "Tactics", "Sentiment", "Skulduggery"), 40, listOf("Shuji", "Rituals", "Kata"), listOf("Bushi", "Shinobi"), listOf("Assess Strengths"), listOf(listOf("Striking as Air", "Striking as Fire")), listOf(1) , listOf("Deceitful Strike", "Spiteful Loss"), listOf("Deadly Sting", "Iaijutsu Cut: Rising Blade"), listOf("Cunning Distraction", "All Shall Fear Me"), listOf("A Samurai's Fate", "Rallying Cry"), listOf("Stillness of Death", "Hidden in Smoke"), "Way of the Scorpion: When you exploit a target's disadvantage (see Core p100) as part of an initiative check for a duel or an Attack action, you do not need to spend a Void point and you may reroll additional dice up to your school rank."),

        IdeTrader ("Ide Trader", "Ide", "Unicorn", listOf("Air","Water"), 5, listOf("Commerce", "Courtesy", "Games", "Labor", "Ranged", "Medicine", "Survival"), 45, listOf("Kata", "Rituals", "Shuji"), listOf("Courtier"), listOf("Tributaries of Trade"), listOf(listOf("Cadence", "Shallow Waters")), listOf(1) , listOf("Feigned Opening", "Hawk's Precision"), listOf("Ebb and Flow", "Lady Shinjo's Speed (Unicorn)"), listOf("Pillar of Calm", "All Arts Are One"), listOf("Sear the Wound", "Regal Bearing"), listOf("Bend with the Storm", "The Immovable Hand of Peace"), "Ignore the Forbidden quality when acquiring and handling items. When acquiring, selling, or gifting an item, you may treat its rarity as reduced or increased by your school rank."),
        IuchiMeishodoMaster ("Iuchi Meishodo Master", "Iuchi", "Unicorn", listOf("Earth","Water"), 3, listOf("Aesthetics", "Design", "Melee", "Meditation", "Survival", "Theology"), 40, listOf("Invocations", "Rituals", "Shuji"), listOf("Shugenja", "Artisan"), listOf("Commune with the Spirits"), listOf(listOf("Grasp of Earth", "Jurojin's Balm", "The Rushing Wave"), listOf("Ancestry Unearthed", "Well of Desire")), listOf(2, 1) , listOf("Sympathetic Energies", "Cleansing Rite"), listOf("Hands of the Tides", "Artisan's Appraisal"), listOf("Dazzling Performance", "Rise, Earth"), listOf("Rouse the Soul", "A Samurai's Fate"), listOf("The Soul's Blade", "Ever Changing Waves"), "As a downtime activity, you may make a TN 2 Design check using any ring to bind a spirit to an inanimate vessel, creating a meishodo talisman for one invocation of that Element that you have learned. While you have the talisman in your possession, reduce the TN of checks to activate that invocation by 1. You can give the talisman to another shugenja, allowing them to perform that invocation even if they have not learned it and reducing the TN to activate it by 1, but the talisman ceases to function after a number of uses equal to your school rank. You can sustain a number of meishodo talismans up to your school rank. You can only have one meishodo talisman for any single invocation."),
        MotoConqueror ("Moto Conqueror", "Moto", "Unicorn", listOf("Fire","Water"), 5, listOf("Command", "Fitness", "Performance", "Melee", "Unarmed", "Survival", "Tactics"), 35, listOf("Kata", "Rituals", "Shuji"), listOf("Bushi"), listOf("All in Jest"), listOf(listOf("Lightning Raid", "Slippery Maneuvers")), listOf(1) , listOf("Crescent Moon Style", "Stirring the Embers"), listOf("Heartpiercing Strike", "Veiled Menace Style"), listOf("Bravado", "Dazzling Performance"), listOf("Striking as Void", "Crashing Wave Style"), listOf("Sear the Wound", "Buoyant Arrival"), "When performing an Attack action during a skirmish or mass battle, you may spend O as follows: O: Choose an enemy other than your target whom you can perceive. Increase the TN of that enemy's Attack checks targeting you by your school rank until the start of your next turn."),
        ShinjoOutrider ("Shinjo Outrider", "Shinjo", "Unicorn", listOf("Earth","Fire"), 5, listOf("Commerce", "Melee", "Ranged", "Medicine", "Skulduggery", "Survival", "Tactics"), 40, listOf("Kata", "Rituals", "Shuji"), listOf("Bushi", "Courtier"), listOf("Lady Shinjo's Speed (Unicorn)"), listOf(listOf("Striking as Fire", "Striking as Water")), listOf(1) , listOf("Pelting Hail Style", "Cadence"), listOf("Flowing Water Strike", "Dazzling Performance"), listOf("Crashing Wave Style", "Crimson Leaves Strike"), listOf("Bend with the Storm", "Bravado"), listOf("Pin the Fan", "Rouse the Soul"), "Once per scene, before rolling dice, you may declare that you are directing your horse (who must be present) to aid in a task and describe how its efforts help in those circumstances. Reduce the TN of the check by your school rank."),
        UtakuBattleMaiden ("Utaku Battle Maiden", "Utaku", "Unicorn", listOf("Air","Earth"), 5, listOf("Command", "Fitness", "Government", "Melee", "Meditation", "Smithing", "Survival"), 50, listOf("Kata", "Rituals", "Shuji"), listOf("Bushi"), listOf("Warrior's Resolve"), listOf(listOf("Crescent Moon Style", "Iron Forest Style")), listOf(1) , listOf("Lady Shinjo's Speed (Unicorn)", "Striking as Air"), listOf("Thunderclap Strike", "Rushing Avalanche Style"), listOf("Pillar of Calm", "Touchstone of Courage"), listOf("Soul Sunder", "Breath of Wind Style"), listOf("Rouse the Soul", "Bend With The Storm"), "When you succeed at an Attack action check, add bonus successes equal to the number of range bands you have moved this round, to a maximum of your school rank. During a duel or mass battle, if you are mounted on your steed, you always count as having moved a number of range bands equal to your school rank this turn. Utaku Steed gives skilled assistance to a mounted Battle Maiden."),
        MotoAvenger ("Moto Avenger", "Moto", "Unicorn", listOf("Air","Earth"), 3, listOf("Courtesy", "Melee", "Sentiment", "Culture", "Sentiment", "Theology", "Survival"), 44, listOf("Air and Earth Invocations", "Shuji", "Rituals"), listOf("Shugenja"), listOf("Grasp of Earth", "Tempest of Air", "Ancestry Unearthed", "Honest Assessment"), listOf(), listOf(0) , listOf("Bind the Shadow", "Caress of Earth"), listOf("Essence of Jade", "Touchstone of Courage"), listOf("Earthquake", "Earth Becomes Sky"), listOf("Rise, Air", "Wolf's Proposal"), listOf("Rouse the Soul", "Tomb of Jade"), "Hands of Earth and Sky: When you perform an invocation that targets at least one other character, if you succeed, you may nourish or drain: If you nourish, you may receive fatigue up to your school rank. One target removes fatigue equal to the amount you received. If you drain, you may remove an amount of fatigue from yourself up to your school rank. One target receives fatigue equal to the amount you removed."),

        MiyaCartographer ("Miya Cartographer", "Miya", "Imperial", listOf("Air","Earth"), 5, listOf("Aesthetics", "Composition", "Culture", "Fitness", "Government", "Seafaring", "Survival"), 50, listOf("Kata", "Rituals", "Shuji"), listOf("Artisan", "Courtier"), listOf(), listOf(listOf("Striking as Earth", "Artisan's Appraisal"), listOf("Warrior's Resolve", "Civility Foremost")), listOf(1, 1) , listOf("Slippery Maneuvers", "Threshold Barrier"), listOf("The Wind Blows Both Ways", "Feigned Opening"), listOf("Crimson Leaves Strike", "All Arts Are One"), listOf("Bend with the Storm", "Regal Bearing"), listOf("Awe of Heaven (Imperial)", "Bravado"), "You always know which way is north, and you are always able to find a landmark useful for navigation. When making a check to recall or ascertain geographical, political, or societal information you may add a number of kept d set to O or S results equal to your school rank."),
        MiyaHerald ("Miya Herald", "Miya", "Imperial", listOf("Air","Water"), 5, listOf("Command", "Composition", "Courtesy", "Fitness", "Seafaring", "Sentiment", "Survival"), 50, listOf("Kata", "Rituals", "Shuji"), listOf("Courtier"), listOf(), listOf(listOf("Cadence", "Honest Assessment"), listOf("Shallow Waters", "Weight of Duty")), listOf(1, 1) , listOf("Feigned Opening", "Courtier's Resolve"), listOf("Ebb and Flow", "Tributaries of Trade"), listOf("Awe of Heaven (Imperial)", "The Wind Blows Both Ways"), listOf("Buoyant Arrival", "Pillar of Calm"), listOf("Sear the Wound", "The Immovable Hand of Peace"), "Once per round, after a character at range 0-4 succeeds on an Attack or Scheme action check, you may cause them to receive strife equal to your school rank."),
        OtomoSchemer ("Otomo Schemer", "Otomo", "Imperial", listOf("Air","Fire"), 5, listOf("Command", "Composition", "Courtesy", "Culture", "Design", "Government", "Sentiment"), 45, listOf("Kata", "Rituals", "Shuji"), listOf("Courtier"), listOf("Slippery Maneuvers"), listOf(listOf("Courtiers Resolve", "Stirring the Embers")), listOf(1) , listOf("Civility Foremost", "Tea Ceremony"), listOf("Awe of Heaven", "Prey on the Weak"), listOf("Regal Bearing", "The Wind Blows Both Ways"), listOf("Buoyant Arrival", "Wolf's Proposal"), listOf("Sear the Wound", "The Immovable Hand of Peace"), "You never forfeit honor or glory in order to lie or decieve for the good of the Emperor and Empire (in your opinion). However you must forfeit twice as much honor or glory to lie for your personal gain (again, in your opinion). When a character stakes or forfeits an amount of honor or glory in order to act against your desires, you may force them to increase that amount by your school rank."),
        SeppunAstrologer ("Seppun Astrologer", "Seppun", "Imperial", listOf("Air","Water"), 3, listOf("Composition", "Government", "Medicine", "Meditation", "Sentiment", "Theology"), 40, listOf("Kata", "Rituals", "Shuji"), listOf("Shugenja", "Artisan"), listOf("Bind the Shadow", "Divination", "Commune with the Spirits", "Threshold Barrier"), listOf(listOf("Dominion of Suijin", "Jade Strike")), listOf(1) , listOf("Heart of the Water Dragon", "Ancestry Unearthed"), listOf("Ebb and Flow", "Symbol of Earth"), listOf("False Realm of the Fox Spirits", "Vapor of Nightmares"), listOf("Tomb of Jade", "A Samurai's Fate"), listOf("Sear the Wound", "The Soul's Blade"), "At the beginning of a game session or as a downtime activity, you may make a TN1 Theology check using any ring. If you succeed, choose a number of kept dice up to your school rank to reserve. Until the end of the game session or the next downtime scene, when any character makes a skill check using the chosen ring, you may replace one or more kept dice with the same number of reserved dice of the same type."),
        SeppunPalaceGuard ("Seppun Palace Guard", "Seppun", "Imperial", listOf("Earth","Void"), 5, listOf("Fitness", "Melee", "Ranged", "Unarmed", "Meditation", "Sentiment", "Tactics"), 50, listOf("Kata", "Rituals", "Shuji"), listOf("Bushi"), listOf(), listOf(listOf("Iaijutsu Cut: Crossing Blade", "Iaijutsu Cut: Rising Blade"), listOf("Ancestry Unearthed", "Honest Assessment")), listOf(1, 1) , listOf("Crescent Moon Style", "Weight of Duty"), listOf("Crimson Leaves Strike", "Touchstone of Courage"), listOf("Iron in the Mountains Style", "Threshold Barrier"), listOf("Soul Sunder", "A Samurai's Fate"), listOf("Rouse the Soul", "The Immovable Hand of Peace"), "When you succeed on an Initiative check during a skirmish or duel, add bonus successes equal to your school rank."),

        WorldlyRonin ("Worldly Ronin", "Other", "Other", listOf("Any","Any"), 5, listOf("Command", "Fitness", "Labor", "Melee", "Ranged", "Unarmed", "Skulduggery"), 30, listOf("Kata", "Rituals", "Shuji"), listOf("Bushi", "Courtier"), listOf(), listOf(listOf("Pelting Hail Style", "Crescent Moon Style"), listOf("All in Jest", "Honest Assessment", "Stirring the Embers", "Rustling of Leaves")), listOf(1, 1) , listOf("Open Hand Style", "Shallow Waters"), listOf("All Arts Are One", "Iron Forest Style"), listOf("A Samurai's Fate", "Dazzling Performance"), listOf("Striking as Void", "Crimson Leaves Strike"), listOf("Sear the Wound", "Buoyant Arrival"), "Choose one bonus curriculum skill; this skill henceforth counts as part of the Worldly Ronin Path curriculum for you at all ranks. Each time your school rank increases, choose one additional bonus curriculum skill this way. When you make a check using one of your bonus curriculum skills, you may negate 1 Strife symbol."),
        FortunistMonk ("Fortunist Monk", "Other", "Other", listOf("Earth","Water"), 4, listOf("Courtesy", "Culture", "Unarmed", "Meditation", "Survival", "Theology"), 40, listOf("Kata", "Rituals", "Shuji"), listOf("Monk"), listOf("Open Hand Style", "Cleansing Rite", "Threshold Barrier"), listOf(listOf("Shallow Waters", "Stirring the Embers")), listOf(1) , listOf("Crescent Moon Style", "Commune with the Spirits"), listOf("All Arts Are One", "Rushing Avalanche Style"), listOf("Regal Bearing", "Ebb and Flow"), listOf("Buoyant Arrival", "Pillar of Calm"), listOf("Rouse the Soul", "Soul Sunder"), "You have gained the goodwill of the Fortune you serve, who grants you certain Invocations. When you make a check to use an Invocation you learned in this way, add additional bonus successes equal to your school rank. Select a Fortune to be the primary object of your veneration and choose one appropriate Invocation (Emerald Empire p237) for which you meet the rank prerequisite. You learn that Invocation without paying its XP cost. Each time your school rank increases, you gain one additional invocation this way."),
        ShinseistMonk ("Shinseist Monk", "Other", "Other", listOf("Earth","Void"), 4, listOf("Aesthetics", "Composition", "Fitness", "Unarmed", "Meditation", "Theology"), 40, listOf("Kata", "Rituals", "Kiho"), listOf("Monk"), listOf("Striking as Earth"), listOf(listOf("Cleansing Spirit", "Earth Needs No Eyes", "Ki Protection")), listOf(2) , listOf("Earthen Fist", "Riding the Clouds"), listOf("All Arts Are One", "Cleansing Rite"), listOf("Grasp the Earth Dragon", "Way of the Willow"), listOf("Pillar of Calm", "Way of the Falling Star"), listOf("Rouse the Soul", "The Immovable Hand of Peace"), "When you spend a Void point to Seize the Moment (Core p36) you may also treat your ranks in the skill you are using as being equal to your school rank, If your ranks in the skill are equal to or higher than your school rank, or if you have 5 ranks in the skill, you may add one kept d set to an O result instead."),
        KolatSaboteur ("Kolat Saboteur", "Other", "Other", listOf("Air","Water"), 5, listOf("Commerce", "Fitness", "Melee", "Ranged", "Medicine", "Meditation", "Skulduggery"), 20, listOf("Kata", "Shuji"), listOf("Shinobi"), listOf("Veiled Menace Style", "Skulk", "Cadence"), listOf(), listOf(0) , listOf("Deadly Sting", "Shallow Waters"), listOf("Noxious Clouds", "Tributaries of Trade"), listOf("Ebb and Flow", "Spin the Web (Kolat)"), listOf("Silencing Stroke", "Wolf's Proposal"), listOf("Buoyant Arrival"), "Once per game session at the beginning of a scene, you may reveal that an NPC in that scene is the target of your current assignment. The GM then decides what your assignment entails, such as sabotaging the targets current activities, framing them for a crime, killing them, or even making sure they survive to play their part in a long and sinister plot. Until the end of the session, when you make a skill check targeting the chosen NPC, you may reroll a number of dice up to your school rank"),
        MercenaryNinja ("Mercenary Ninja", "Other", "Other", listOf("Air","Any"), 5, listOf("Fitness", "Melee", "Ranged", "Unarmed", "Medicine", "Skulduggery", "Survival"), 20, listOf("Ninjutsu", "Rituals", "Kata"), listOf("Shinobi"), listOf("Skulk"), listOf(listOf("Cadence", "Shallow Waters")), listOf(1) , listOf("Beware the Smallest Mouse", "Like a Ghost"), listOf("Silent Elimination", "Veiled Menace Style"), listOf("Feigned Opening", "Slicing Wind Kick"), listOf("Hidden in Smoke", "Breath of Wind Style"), listOf("Foreseen Need", "Striking as Void"), "Disciple of Darkness: When you perform a check to hide, move stealthily, or deceive others as to your true identity, you may suffer a number of strife up to your school rank to choose that many characters targeted by the check. Treat each chosen character's vigilance as 1 lower while resolving the check."),
        KitsuneImpersonator ("Kitsune Impersonator", "Other", "Other", listOf("Air","Fire"), 3, listOf("Courtesy", "Games", "Performance", "Unarmed", "Survival", "Theology"), 30, listOf("Invocations", "Rituals", "Shuji"), listOf("Courtier", "Shugenja"), listOf("Natures Touch", "Token of Memory", "Commune with the Spirits"), listOf(), listOf(0) , listOf("Fanning the Flames", "All in Jest"), listOf("Dazzling Performance", "False Realm of the Fox Spirits"), listOf("Crashing Wave Style", "Regal Bearing"), listOf("Disappearing World Style", "Bravado"), listOf("Soul Sunder", "Buoyant Arrival"), "Disadvantage: False Identity (Emerald Empire, p247). Your true form is that of a large fox with up to eight tails if you are a full-blooded kitsune, or a human with certain furry traits if you possess human ancestry as well. As a Scheme and Support action you may transform between your human and true forms, or into another silhouette 1 or 2 natural creature at the GM discretion (you cannot mimic specific individuals). Observers with vigilance lower than or equal to your school rank plus your ranks in Performance do not detect any flaws in your facade. However certain key features persist across all your forms. If you become Compromised, your disguise slips, subtly revealing your true tails, ears, feet or shadow."),
        WanderingBlade ("Wandering Blade", "Other", "Other", listOf("Earth","Any"), 5, listOf("Fitness", "Melee", "Ranged", "Unarmed", "Meditation", "Performance", "Smithing"), 35, listOf("Kata", "Rituals", "Shuji"), listOf("Bushi"), listOf("Wanderer's Resolve"), listOf(listOf("Striking as Air", "Striking as Earth", "Striking as Water", "Striking as Fire")), listOf(1) , listOf("Bellow of Resolve", "Tactical Assessment"), listOf("Rushing Ox Style", "Wayfarer's Path"), listOf("Iron in the Mountains Style", "Tonight, I am Your Opponent"), listOf("Bravado", "Void Embrace Style"), listOf("Bond of Heroes", "Roar of Encouragement"), "Signature Weapon: Choose a signature weapon category (or unarmed) with GM approval. When using a weapon from this category for an Attack action or Performance check, roll one additional skill die. Additionally, when making such a check, you may suffer fatigue up to your school rank to alter that many results of your kept dice to O results."),
        StudentoftheTalon ("Student of the Talon", "Other", "Other", listOf("Air","Water"), 5, listOf("Fitness", "Melee", "Ranged", "Meditation", "Sentiment", "Skulduggery", "Survival"), 30, listOf("Kata", "Rituals", "Shuji"), listOf("Bushi", "Shinobi"), listOf("Skulk"), listOf(listOf("Soaring Slice", "Hawk's Precision")), listOf(1) , listOf("Flowering Deceptions", "Chaotic Scattering"), listOf("Heartpiercing Strike", "Swirling Viper Style"), listOf("Wasp's Spite Style", "Eyeless Sight Shot"), listOf("Wolf's Proposal", "Falling Heavens Shot"), listOf("Deadly Sting", "Watch My Back"), "Piercing Insight: Once per round, in a skirmish, when you inflict a critical strike on a character at range 2-5, or when a character at range 2-5 inflicts a critical strike on you, you may increase or decrease the severity by your school rank. "),
        TreasureHunter ("Treasure Hunter", "Other", "Other", listOf("Air","Water"), 5, listOf("Commerce", "Courtesy", "Fitness", "Games", "Melee", "Sentiment", "Skulduggery"), 27, listOf("Kata", "Rituals", "Shuji"), listOf(), listOf("Tactical Assessment"), listOf(listOf("All in Jest", "Rustling of Leaves")), listOf(1) , listOf("Striking as Air", "Chaotic Scattering"), listOf("Daring Swing", "Reckless Lunge"), listOf("Dazzling Performance", "Laughing Fox Style"), listOf("Regal Bearing", "Ruse of the Moon's Reflection"), listOf("Watch My Back", "Roar of Encouragement"), "Risk and Reward: You have an uncanny sense for dangerous situations. Your Vigilance and Focus are increased by your school rank unless you are Compromised."),
        SchoolofLeaves ("School of Leaves", "Other", "Other", listOf("Fire","Air"), 5, listOf("Fitness", "Melee", "Ranged", "Performance", "Sentiment", "Skulduggery", "Survival"), 26, listOf("Kata", "Rituals", "Shuji"), listOf("Shinobi", "Courtier"), listOf("Skulk", "Deadly Sting"), listOf(listOf("Honest Assessment", "Whispers of Court")), listOf(1) , listOf("Prey on the Weak", "Rustling of Leaves"), listOf("Staggering Shot", "Crimson Leaves Strike"), listOf("Noxious Cloud", "Wasp's Spite Style"), listOf("Iaijutsu Cut: Reverse Draw", "Ruse of Moon's Reflection"), listOf("Bend with the Storm", "Silencing Stroke"), "Tactical Cover: While you are in Obscuring terrain, you may treat your physical resistance as increased by your school rank."),
        VoiceoftheWilds ("Voice of the Wilds", "Other", "Other", listOf("Any","Any"), 3, listOf("Composition", "Courtesy", "Games", "Meditation", "Sentiment", "Theology"), 35, listOf("Rituals", "Shuji"), listOf("Shugenja", "Courtier"), listOf(), listOf(listOf("Commune with the Spirits", "Divination"), listOf("Well of Desire", "Weight of Duty", "Rustling of Leaves", "Sensational Distraction")), listOf(1, 2) , listOf("Nature's Touch", "Threshold Barrier"), listOf("Earth Becomes Sky", "Tactical Assessment"), listOf("Fury of Osano-wo", "Hands of the Tides"), listOf("Mentor's Guidance", "False Realm of the Fox Spirits"), listOf("Ever Changing Waves"), "Naturally Attuned: As a downtime activity you may select any number of invocations with total school rank prerequisites equal to double your school rank. You can perform these invocations as if you knew them."),
        ArtisanoftheRoads ("Artisan of the Roads", "Other", "Other", listOf("Fire","Any"), 5, listOf("Aesthetics", "Courtesy", "Commerce", "Composition", "Culture", "Design", "Smithing"), 30, listOf("Kata", "Rituals", "Shuji"), listOf("Artisan"), listOf("Fanning the Flames"), listOf(listOf("Shallow Waters", "Whispers of Court")), listOf(1) , listOf("Fluent Bargaining", "Artisan's Appraisal"), listOf("Dazzling Performance", "Improvised Assault"), listOf("Bravado", "Wheeling Sweep"), listOf("Mentor's Guidance", "Laughing Fox Style"), listOf("Roar of Encouragement", "Rouse the Soul"), "Resourceful Artistry: Once per game session, when performing a downtime activity to craft, you may scavenge supplies for your craft worth an amount of koku equal to your school rank. This might include finding plants to make paints, wood for carvings, horsehair for brushes, or convincing peasants to give you parchment, ink or other supplies."),
        MysticoftheMountains ("Mystic of the Mountains", "Other", "Other", listOf("Void","Air"), 4, listOf("Melee", "Unarmed", "Performance", "Sentiment", "Survival", "Theology"), 40, listOf("Kata", "Rituals", "Shuji"), listOf("Monk", "Courtier"), listOf("Cleansing Rite", "Artisan's Approval"), listOf(listOf("Ki Protection", "The Great Silence"), listOf("Honest Assessment", "Stirring the Embers")), listOf(1, 1) , listOf("Way of the Earthquake", "Air Fist"), listOf("Way of the Willow", "Channel the Fire Dragon"), listOf("Way of the Falling Star", "Ride the Water Dragon"), listOf("Touch the Void Dragon", "Pillar of Calm"), listOf("Way of the Edgeless Sword", "Bend with the Storm"), "Unexpected Wisdom: You are a wealth of wisdom, which you dispense a number of times per game session equal to your school rank. On your turn or at any appropriate time during a narrative scene, you may dispense a small bit of wisdom to a character who can hear you and has not benefitted from this ability this scene. The next time a character, including yourself, employs that wisdom they may reduce the TN of that check by 1 and may negate a number of strife up to your ranks in Sentiment or Theology (your choice)."),
        UjikDiviner ("Ujik Diviner", "Other", "Other", listOf("Void","Water"), 3, listOf("Command", "Games", "Meditation", "Performance", "Sentiment", "Theology"), 40, listOf("Earth and Water Invocations", "Rituals", "Shuji"), listOf("Sage"), listOf("Ancestry Unearthed"), listOf(listOf("Commune with the Spirits", "Embrace of Kenro-Ji-Jin", "Caress of Earth", "Jurojin's Balm", "Wall of Earth"), listOf("Dance of Seasons", "Heart of the Water Dragon", "Dominion of Suijin", "Inari's Blessing", "Reflections of P'an Ku")), listOf(2, 2) , listOf("Divination", "Fukurokujin's Wit"), listOf("Ebb and Flow", "Mask of Wind"), listOf("Chaotic Scattering", "Vapor of Nightmares"), listOf("Laughing Fox Style", "Mentor's Guidance"), listOf("Roar of Encouragement", "Bond of Heroes"), "Seer of the Lords of Death: You can channel rituals in the same way as invocations (Core p189). Once per scene, when you channel, you may receive fatigue up to your schol rank. If you do, you may immediately make another check to perform an invocation of the same element using the reserved dice from your channel. For each fatigue received this way, you may add one kept die set to a S result."),
        QamaristShieldBearer ("Qamarist Shield Bearer", "Other", "Other", listOf("Earth","Void"), 5, listOf("Command", "Fitness", "Melee", "Unarmed", "Meditation", "Tactics", "Theology"), 50, listOf(), listOf("Bushi", "Sage"), listOf("Crescent Moon Style", "Courtier's Resolve"), listOf(), listOf(0) , listOf("Divination", "Wanderer's Resolve"), listOf("Goading Taunt", "Iron Shell Style"), listOf("Deflective Defense", "Iron in the Mountains Style"), listOf("Bonebreaker Style", "Mentor's Guidance"), listOf("Fortitude Draught", "Bond of Heroes"), "Aklah's Teachings: Once per round after an Attack action check against you fails, if you have a shield readied and the attack is at range 0-1, you may shield bash. If you do, the target suffers physical damage equal to your ranks in Fitness plus your school rank."),
        QamaristAlchemist ("Qamarist Alchemist", "Other", "Other", listOf("Earth","Fire"), 3, listOf("Courtesy", "Culture", "Ranged", "Medicine", "Meditation", "Theology"), 52, listOf("Kata", "Rituals", "Shuji"), listOf("Sage"), listOf("Balancing Salve", "Cleansing Rite", "Illuminate the Way", "Truth Burns Through Lies"), listOf(), listOf(0) , listOf("Weight of Duty", "Wanderer's Resolve"), listOf("Fortitude Draught", "Boar's Wrath Style"), listOf("Breath of Wind Style", "Look Out!"), listOf("Restorative Transmutation", "Pillar of Calm"), listOf("Mentor's Guidance", "Void Embrace Style"), "Creative Execution: When making a check to perform a ritual, you may receive fatigue up to your school rank to add that many kept dice to O results."),
        IvoryKingdomSage ("Ivory Kingdom Sage", "Other", "Other", listOf("Void","Earth"), 5, listOf("Composition", "Command", "Courtesy", "Melee", "Unarmed", "Meditation", "Theology"), 50, listOf("Kata", "Kiho", "Rituals"), listOf("Sage", "Bushi"), listOf("Threshold Barrier"), listOf(listOf("Cleansing Spirit", "Earth Needs No Eyes", "Earthen Fist")), listOf(2) , listOf("Landslide Strike", "Bellow of Resolve"), listOf("Rider's Haste", "Lord Hida's Grasp (Crab)"), listOf("Thunderous Hooves Style", "Cleansing of Coral and Gold"), listOf("Striking as Void", "Mentor's Guidance"), listOf("Touch the Void Dragon", "Buoyant Arrival"), "Gift of Inner Power: You can infuse other characters with your inner energy. After you perform a check to activate one of your kiho, you can receive fatigue up to your school rank and choose another character at range 0-1. If you do, that character gains the enhancement effect of your kiho in your stead (you may still resolve the burst effect, if able). This effect persists a number of rounds equal to the amount of fatigue you received this way plus your ranks in Meditation. Only one character may benefit from your kiho at a time."),
        IvoryKingdomDancingBladesTradition ("Ivory Kingdom Dancing Blades Tradition", "Other", "Other", listOf("Earth","Fire"), 5, listOf("Command", "Culture", "Melee", "Ranged", "Medicine", "Performance", "Seafaring"), 45, listOf("Kata", "Rituals", "Shuji"), listOf("Bushi"), listOf(), listOf(listOf("Hawk's Precision", "Warrior's Resolve"), listOf("Stirring the Embers", "Honest Assessment")), listOf(1, 1) , listOf("Eyes Up!", "Rider's Haste"), listOf("Rushing Ox Style", "Summoning Mantra: Celestial Implement"), listOf("Daring Swing", "Bravado"), listOf("Swirling Tempest Style", "Roar of Encouragement"), listOf("Sear the Wound", "The Immovable Hand of Peace"), "Flurry of Steel: Once per scene when performing an Attack action, you may choose a number of additional enemies up to your school rank in range of your weapon as targets of that Attack action."),

        StormFleetSailor ("Storm Fleet Sailor", "Mantis", "Minor", listOf("Fire","Water"), 5, listOf("Commerce", "Fitness", "Games", "Labor", "Melee", "Ranged", "Seafaring"), 35, listOf("Kata", "Rituals", "Shuji"), listOf("Bushi"), listOf("Pelting Hail Style"), listOf(listOf("All in Jest", "Stirring the Embers")), listOf(1) , listOf("Skulk", "Shallow Waters"), listOf("Flowing Water Strike", "Osano-Wo's Boast (Mantis)"), listOf("Bravado", "Heartpiercing Strike"), listOf("Buoyant Arrival", "Crashing Wave Style"), listOf("Rouse the Soul", "Sear the Wound"), "Once per round when making a Trade skill check, if you are not Compromised, you may receive a number of strife up to your school rank to reroll that many rolled dice. Mantis DLC"),
        TideSeer ("Tide Seer", "Mantis", "Minor", listOf("Air","Water"), 3, listOf("Commerce", "Fitness", "Games", "Labor", "Melee", "Seafaring", "Theology"), 40, listOf("Air & Water Invocations", "Rituals", "Shuji"), listOf("Shugenja"), listOf("Domination of Suijin", "Tempest of Air", "Commune with the Spirits", "Divination"), listOf(listOf("Bo of Water", "Yari of Air", "Path to Inner Peace")), listOf(1) , listOf("Summon Fog", "Reflections of P'an Ku"), listOf("Hand of the Tides", "Call upon the Wind"), listOf("Fury of Osano-Wo", "Osano-Wo's Boast (Mantis)"), listOf("Wrath of Kaze-no-Kami", "Rise, Water"), listOf("Ever-Changing Waves", "Rise, Air"), "When an invocation technique you perform would affect 'each character' or 'each other character' at a specified range, you may exclude a number of characters up to your school rank from all effects of the invocation except for spiritual backlash (Core p190). Mantis DLC"),
        ToritakaPhantomHunter ("Toritaka Phantom Hunter", "Toritaka", "Minor", listOf("Air","Water"), 3, listOf("Culture", "Government", "Melee", "Sentiment", "Survival", "Theology"), 40, listOf("Invocations", "Rituals", "Shuji"), listOf("Shugenja"), listOf("Cleansing Rite", "Commune with the Spirits", "Tea Ceremony", "Courtier's Resolve", "By the Light of the Lord Moon"), listOf(), listOf(0) , listOf("Bo of Water", "Threshold Barrier"), listOf("Essence of Jade", "Striking as Air"), listOf("Rise, Water", "Crescent Moon Style"), listOf("Rouse the Soul", "Soul Sunder"), listOf("Flowing Water Strike", "Wrath of Kaze-no-Kami"), "Eyes of Yotogi: Otherworldly beings treat your vigilance as being increased by your school rank. When you make a check to search for Otherworldly beings, or make an Initiative check in a conflict against them, if you succeed, add bonus successes equal to your school rank."),
        KasugaSmuggler ("Kasuga Smuggler", "Kasuga", "Minor", listOf("Air","Water"), 5, listOf("Commerce", "Culture", "Courtesy", "Melee", "Seafaring", "Skulduggery"), 29, listOf("Kata", "Rituals", "Shuji"), listOf("Bushi"), listOf("Rushing Avalanche Style"), listOf(listOf("Honest Assessment", "Well of Desire")), listOf(1) , listOf("Coiling Serpent Style", "Courtier's Resolve"), listOf("Ebb and Flow", "Tributaries of Trade"), listOf("All Arts Are One", "Breath of Wind Style"), listOf("Buoyant Arrival", "Regal Bearing"), listOf("Bend with the Storm", "The Immovable Hand of Peace"), "You never need to stake glory to publicly use a Trade skill, so long as you are doing so as part of your duty to your clan. Once per scene, you may add a number of kept d set to O results equal to your school rank to a check to interact with one or more gaijin, peasants, merchants, burakumin, or any other character with status of 20 or lower."),
        ShikaMatchmaker ("Shika Matchmaker", "Shika", "Other", listOf("Air","Water"), 3, listOf("Composition", "Courtesy", "Culture", "Meditation", "Sentiment", "Theology"), 50, listOf("Shuji", "Rituals", "Air & Water Invocations"), listOf("Courtier", "Shugenja"), listOf("The Ties that Bind", "Yari of Air"), listOf(listOf("Blessed Wind", "Path to Inner Peace", "Sympathetic Energies", "Tempest of Air")), listOf(2) , listOf("Ancestry Unearthed", "Fun and Games"), listOf("Strike the Tsunami", "Civility Foremost"), listOf("Rise, Air", "The Wind Blows Both Ways"), listOf("Wrath of Kaze-no-Kami", "Treaty Signing"), listOf("Buoyant Arrival", "Formal Tea Ceremony"), "Gift of Musubi-no-Kami: You may perform the 'Ties that Bind' ritual as an action, instead of as a downtime activity. When you make a check to perform this ritual, you may add kept d set to O results equal to your school rank."),
        ShikaSpeardancer ("Shika Speardancer", "Shika", "Other", listOf("Air","Fire"), 5, listOf("Melee", "Meditation", "Skulduggery", "Survival", "Fitness", "Sentiment", "Courtesy"), 35, listOf("Shuji", "Rituals", "Kata"), listOf("Bushi", "Shinobi"), listOf("Trip the Leg"), listOf(listOf("Striking as Air", "Striking as Fire")), listOf(1) , listOf("Like a Ghost", "Soaring Slice"), listOf("To Float or Sink", "Crescent Moon Style"), listOf("Slicing Wind Kick", "Pole Vault"), listOf("Rouse the Soul", "Disappearing World Style"), listOf("Silent Elimination", "The Ties that Bind"), "Typhoon in the Bamboo Grove: When making a Martial Arts (Melee) or Fitness check, you may spend O O to cause a number of characters no greater than your school rank and within range of your readied weapon to suffer the Dazed condition."),}


